KUDASAI = "ください"
KURU_KANJI = "来"

# IRREGULAR VERB ENDINGS
SURU_ENDING = "する"
KURU_ENDING = "くる"
KURU_KANJI_ENDING = "来る"

# (POLITE) MASU FORM ENDINGS
MASU_POSITIVE_NONPAST = "ます"
MASU_NEGATIVE_NONPAST = "ません"
MASU_POSITIVE_PAST = "ました"
MASU_NEGATIVE_PAST = "ませんでした"

# (PLAIN) KATTA FORM ENDING
KATTA_ENDING = "かった"

# (PLAIN) NAI ENDING
NAI_ENDING = "ない"

# VOLITIONAL FORM ENDINGS
VOLITIONAL_POLITE_ENDING = "ましょう"
VOLITIONAL_POLITE_COPULA = "でしょう"
VOLITIONAL_PLAIN_COPULA = "だろう"
VOLITIONAL_ICHIDAN_PLAIN_ENDING = "よう"
VOLITIONAL_SURU_ENDING = "しよう"
VOLITIONAL_KURU_ENDING = "こよう"
VOLITIONAL_KURU_KANJI_ENDING = "来よう"

# POTENTIAL FORM
POTENTIAL_POLITE_ICHIDAN_ENDING = "られます"
POTENTIAL_ICHIDAN_ENDING = "られる"
POTENTIAL_SURU_PLAIN_POSITIVE_ENDING = "できる"
POTENTIAL_SURU_PLAIN_NEGATIVE_ENDING = "できない"
POTENTIAL_SURU_POLITE_POSITIVE_ENDING = "できます"
POTENTIAL_SURU_POLITE_NEGATIVE_ENDING = "できません"
POTENTIAL_KURU_PLAIN_POSITIVE_ENDING = "こられる"
POTENTIAL_KURU_POLITE_POSITIVE_ENDING = "こられます"
POTENTIAL_KURU_PLAIN_NEGATIVE_ENDING = "こられない"
POTENTIAL_KURU_POLITE_NEGATIVE_ENDING = "こられません"
POTENTIAL_KURU_KANJI_PLAIN_POSITIVE_ENDING = "来られる"
POTENTIAL_KURU_KANJI_POLITE_POSITIVE_ENDING = "来られます"
POTENTIAL_KURU_KANJI_PLAIN_NEGATIVE_ENDING = "来られない"
POTENTIAL_KURU_KANJI_POLITE_NEGATIVE_ENDING = "来られません"

# PASSIVE FORM ENDINGS
PASSIVE_ICHIDAN_PLAIN_POSITIVE_ENDING = "られる"
PASSIVE_ICHIDAN_POLITE_POSITIVE_ENDING = "られます"
PASSIVE_ICHIDAN_PLAIN_NEGATIVE_ENDING = "られない"
PASSIVE_ICHIDAN_POLITE_NEGATIVE_ENDING = "られません"

# CAUSATIVE VERB ENDINGS
CAUSATIVE_PLAIN_SURU_ENDING = "させる"
CAUSATIVE_PLAIN_KURU_ENDING = "こさせる"
CAUSATIVE_KURU_NEGATIVE_BASE = "こさせ"
CAUSATIVE_PLAIN_KURU_KANJI_ENDING = "来させる"
CAUSATIVE_KURU_KANJI_NEGATIVE_BASE = "来させ"

# IMPERATIVE VERB ENDINGS
IMPERATIVE_SURU_PLAIN_POSITIVE_ENDING = "しろ"
IMPERATIVE_KURU_PLAIN_POSITIVE_ENDING = "こい"
IMPERATIVE_KURU_KANJI_PLAIN_POSITIVE_ENDING = "来い"

# PROVISIONAL VERB ENDINGS
PROVISIONAL_SURU_PLAIN_POSITIVE_ENDING = "すれば"
PROVISIONAL_SURU_POLITE_POSITIVE_ENDING = "しませば"
PROVISIONAL_KURU_PLAIN_POSITIVE_ENDING = "くれば"
PROVISIONAL_KURU_POLITE_POSITIVE_ENDING = "きませば"
PROVISIONAL_KURU_KANJI_PLAIN_POSITIVE_ENDING = "来れば"
PROVISIONAL_KURU_KANJI_POLITE_POSITIVE_ENDING = "来ませば"
PROVISIONAL_ICHIDAN_PLAIN_NEGATIVE_ENDING = "なければ"

# PASSIVE VERB ENDINGS
PASSIVE_SURU_PLAIN_POSITIVE_ENDING = "される"
PASSIVE_KURU_PLAIN_POSITIVE_ENDING = "こられる"
PASSIVE_KURU_KANJI_PLAIN_POSITIVE_ENDING = "来られる"

# DA COPULA ENDINGS
PLAIN_DA_POSITIVE_ENDING = "だ"
POLITE_DA_POSITIVE_ENDING = "です"
CONDITIONAL_DA_PLAIN_POSITIVE_ENDING = "なら"
PRESUMPTIVE_DA_PLAIN_POSITIVE_ENDING = "だろう"
PRESUMPTIVE_DA_POLITE_POSITIVE_ENDING = "でしょう"
TE_FORM_DA_PLAIN_POSITIVE_ENDING = "で"
TE_FORM_DA_POLITE_POSITIVE_ENDING = "でして"
PAST_DA_PLAIN_POSITIVE_ENDING = "だった"
PAST_DA_POLITE_POSITIVE_ENDING = "でした"
TARA_DA_PLAIN_POSITIVE_ENDING = "だったら"
TARA_DA_POLITE_POSITIVE_ENDING = "でしたら"
PLAIN_DA_NEGATIVE_ENDING = "ではない"
POLITE_DA_NEGATIVE_ENDING = "ではありません"
PAST_DA_PLAIN_NEGATIVE_ENDING = "なかった"
